version: "2"
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - gofmt
    - revive