apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  resourceVersion: "12345"
  uid: "abc-123"
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap"...}
data:
  database_url: "postgres://old-db:5432/app"
  log_level: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
  resourceVersion: "67890"
  uid: "def-456"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx:1.20
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: "production"
status:
  availableReplicas: 2
  readyReplicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP