apiVersion: v1
kind: ConfigMap
metadata:
  name: unchanged-config
  namespace: default
data:
  key: value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: old-config
  namespace: default
data:
  key: old-value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changed-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changed-app
  template:
    metadata:
      labels:
        app: changed-app
    spec:
      containers:
      - name: app
        image: nginx:1.20