name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.x' # Use the latest stable version of Go

    - name: Build
      run: |-
        make build

    - name: Test
      run: |-
        make test/unit

    - name: Format
      run: |-
        make fmt
        # Check if the code is formatted correctly
        git diff --exit-code || (echo "Code is not formatted correctly. Please run 'make fmt' to format the code." && exit 1)

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        args: --out-format=colored-line-number 

    - name: Upload skiff artifact
      uses: actions/upload-artifact@v4
      with:
        name: skiff-binary
        path: skiff

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.50.0/conftest_0.50.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.50.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Download skiff binary
        uses: actions/download-artifact@v4
        with:
          name: skiff-binary
          path: . # Download to the root of the workspace

      - name: Run Integration Tests
        run: |-
          chmod +x ./skiff
          ./test/test-policies/test-policy.sh
